
        INSERT INTO `_traducciones` (`id`, `frase`, `idioma`, `traduccion`) VALUES 
(null, 'cambiar_idioma', 'en_GB', '---'),
(null, 'Editar', 'en_GB', '---'),
(null, 'Ver', 'en_GB', '---'),
(null, 'Bon n°', 'en_GB', '---'),
(null, 'Borrado', 'en_GB', '---'),
(null, 'Enviado', 'en_GB', '---'),
(null, 'En proceso', 'en_GB', '---'),
(null, 'Registrado', 'en_GB', '---'),
(null, 'Todos', 'en_GB', '---'),
(null, 'Bon n°:', 'en_GB', '---'),
(null, 'Nuevo', 'en_GB', '---'),
(null, 'Buscar', 'en_GB', '---'),
(null, 'Estatus', 'en_GB', '---'),
(null, 'Notas', 'en_GB', '---'),
(null, 'Fecha', 'en_GB', '---'),
(null, 'Email', 'en_GB', '---'),
(null, 'Contacto', 'en_GB', '---'),
(null, 'Empresa', 'en_GB', '---'),
(null, 'Ref', 'en_GB', '---'),
(null, '123, sin ceros al inicio', 'en_GB', '---'),
(null, 'Id', 'en_GB', '---'),
(null, 'Busqueda detallada', 'en_GB', '---'),
(null, 'Lista', 'en_GB', '---'),
(null, 'Pedidos', 'en_GB', '---'),
(null, 'index', 'en_GB', '---'),
(null, 'pedidos', 'en_GB', '---'),
(null, 'Logout', 'en_GB', '---'),
(null, 'Cambiar clave', 'en_GB', '---'),
(null, 'Idiomas', 'en_GB', '---'),
(null, 'Inicio', 'en_GB', '---'),
(null, 'cambiar_idioma', 'en_GB', '---'),
(null, 'Editar', 'en_GB', '---'),
(null, 'Ver', 'en_GB', '---'),
(null, 'Bon n°', 'en_GB', '---'),
(null, 'Borrado', 'en_GB', '---'),
(null, 'Enviado', 'en_GB', '---'),
(null, 'En proceso', 'en_GB', '---'),
(null, 'Registrado', 'en_GB', '---'),
(null, 'Todos', 'en_GB', '---'),
(null, 'Bon n°:', 'en_GB', '---'),
(null, 'Nuevo', 'en_GB', '---'),
(null, 'Buscar', 'en_GB', '---'),
(null, 'Estatus', 'en_GB', '---'),
(null, 'Notas', 'en_GB', '---'),
(null, 'Fecha', 'en_GB', '---'),
(null, 'Email', 'en_GB', '---'),
(null, 'Contacto', 'en_GB', '---'),
(null, 'Empresa', 'en_GB', '---'),
(null, 'Ref', 'en_GB', '---'),
(null, '123, sin ceros al inicio', 'en_GB', '---'),
(null, 'Id', 'en_GB', '---'),
(null, 'Busqueda detallada', 'en_GB', '---'),
(null, 'Lista', 'en_GB', '---'),
(null, 'Pedidos', 'en_GB', '---'),
(null, 'index', 'en_GB', '---'),
(null, 'pedidos', 'en_GB', '---'),
(null, 'Logout', 'en_GB', '---'),
(null, 'Cambiar clave', 'en_GB', '---'),
(null, 'Idiomas', 'en_GB', '---'),
(null, 'Inicio', 'en_GB', '---'),
(null, 'System code is incorrect (Licence error)', 'en_GB', 'System code is incorrect (Licence error)'),
(null, 'System code is incorrect', 'en_GB', 'System code is incorrect'),
(null, 'Error Licencia', 'en_GB', 'Error Licencia'),
(null, 'Registrar', 'en_GB', '---'),
(null, 'Una vez la clave cambiada, tendra que volver a conectarse con la nueva clave.', 'en_GB', '---'),
(null, 'Repita aca la nueva clave', 'en_GB', '---'),
(null, 'Repita', 'en_GB', '---'),
(null, 'Letras, números, signos [&é#§çà, etc]', 'en_GB', '---'),
(null, 'Nueva clave', 'en_GB', '---'),
(null, 'Usuario', 'en_GB', '---'),
(null, 'cambiar_clave', 'en_GB', '---'),
(null, '_usuarios', 'en_GB', '---'),
(null, '1', 'en_GB', '1'),
(null, 'Borar', 'en_GB', 'Borar'),
(null, 'Crear', 'en_GB', 'Crear'),
(null, 'Nuevo actualizaciones', 'en_GB', 'Nuevo actualizaciones'),
(null, 'logs, se crean automaticamante, no se puede crear', 'en_GB', 'logs, se crean automaticamante, no se puede crear'),
(null, 'Logs, no se puede editar', 'en_GB', 'Logs, no se puede editar'),
(null, 'Editar logs', 'en_GB', 'Editar logs'),
(null, 'Editar', 'en_GB', '---'),
(null, 'Ver', 'en_GB', '---'),
(null, 'cambiar_idioma', 'en_GB', '---'),
(null, 'Bon n°', 'en_GB', '---'),
(null, 'Borrado', 'en_GB', '---'),
(null, 'Enviado', 'en_GB', '---'),
(null, 'En proceso', 'en_GB', '---'),
(null, 'Registrado', 'en_GB', '---'),
(null, 'Todos', 'en_GB', '---'),
(null, 'Bon n°:', 'en_GB', '---'),
(null, 'Nuevo', 'en_GB', '---'),
(null, 'Buscar', 'en_GB', '---'),
(null, 'Estatus', 'en_GB', '---'),
(null, 'Notas', 'en_GB', '---'),
(null, 'Fecha', 'en_GB', '---'),
(null, 'Email', 'en_GB', '---'),
(null, 'Contacto', 'en_GB', '---'),
(null, 'Empresa', 'en_GB', '---'),
(null, 'Ref', 'en_GB', '---'),
(null, '123, sin ceros al inicio', 'en_GB', '---'),
(null, 'Id', 'en_GB', '---'),
(null, 'Busqueda detallada', 'en_GB', '---'),
(null, 'Lista', 'en_GB', '---'),
(null, 'pedidos', 'en_GB', '---'),
(null, 'Ayuda', 'en_GB', '---'),
(null, 'index', 'en_GB', '---'),
(null, 'home', 'en_GB', '---'),
(null, 'Logout', 'en_GB', '---'),
(null, 'Cambiar clave', 'en_GB', '---'),
(null, 'Idiomas', 'en_GB', '---'),
(null, 'Pedidos', 'en_GB', '---'),
(null, 'Inicio', 'en_GB', '---'),
(null, 'El contenido se genera automaticamnte, no puede agregar', 'en_GB', 'El contenido se genera automaticamnte, no puede agregar'),
(null, 'Ubicación', 'en_GB', 'Ubicación'),
(null, 'folder-open', 'en_GB', 'folder-open'),
(null, 'export_google', 'en_GB', 'export_google'),
(null, 'Olvido el número de pedido', 'en_GB', 'Olvido el número de pedido'),
(null, 'Pedido no puede ser editado', 'en_GB', 'Pedido no puede ser editado'),
(null, 'pedidos_notas', 'en_GB', 'Pedidos_notas'),
(null, 'Páginas', 'en_GB', 'Páginas'),
(null, 'Usado para ingresar al sistema', 'en_GB', 'Usado para ingresar al sistema'),
(null, 'Columnas disponibles', 'en_GB', 'Columnas disponibles'),
(null, 'acción', 'en_GB', 'acción'),
(null, 'grupo', 'en_GB', 'group'),
(null, 'ciudad', 'en_GB', 'ciudad'),
(null, 'id', 'en_GB', 'id'),
(null, 'Buscar un contacto', 'en_GB', 'Buscar un contacto'),
(null, 'Último ingreso', 'en_GB', 'Último ingreso'),
(null, 'Contactos', 'en_GB', 'Contactos'),
(null, 'Cambiar el grupo por:', 'en_GB', 'Cambiar el grupo por:'),
(null, 'Cambiar el grupo por:...', 'en_GB', 'Cambiar el grupo por:...'),
(null, 'Lista de actualizaciones', 'en_GB', 'Lista de actualizaciones'),
(null, 'Ejecutar', 'en_GB', 'Ejecutar'),
(null, 'Requiere', 'en_GB', 'Requiere'),
(null, 'Codigo', 'en_GB', 'Codigo'),
(null, 'actualizaciones', 'en_GB', 'actualizaciones'),
(null, 'Hay una nueva versión, <b><a href="index.php?p=actualizaciones">aca</a></b> para actualizar su sistema', 'en_GB', 'Hay una nueva versión, <b><a href="index.php?p=actualizaciones">aca</a></b> para actualizar su sistema'),
(null, 'Hay una nueva versión, <b><a href="index.php?p=actualizaciones"></a></b> aca para actualizar su sistema', 'en_GB', 'Hay una nueva versión, <b><a href="index.php?p=actualizaciones"></a></b> aca para actualizar su sistema'),
(null, 'Hay una nueva versión, click aca para actualizar su sistema', 'en_GB', 'Hay una nueva versión, click aca para actualizar su sistema'),
(null, 'pedidos_id', 'en_GB', 'pedidos_id'),
(null, 'centro', 'en_GB', 'centro'),
(null, 'empresa', 'en_GB', 'empresa'),
(null, 'contacto', 'en_GB', 'contacto'),
(null, 'No tiene permiso para editar pedidos que no le pertenecen', 'en_GB', 'No tiene permiso para editar pedidos que no le pertenecen'),
(null, 'Pedido no le pertenece, o no tiene permiso para editarlo', 'en_GB', 'Pedido no le pertenece, o no tiene permiso para editarlo'),
(null, 'Pedido no existe o no puede ser editado', 'en_GB', 'Pedido no existe o no puede ser editado'),
(null, '% Traducción', 'en_GB', '% Traducción'),
(null, 'Traducido', 'en_GB', 'Traducido'),
(null, 'Error', 'en_GB', 'Error'),
(null, 'cambiar_idioma', 'en_GB', 'cambiar_idioma'),
(null, 'vendedores', 'en_GB', 'vendedores'),
(null, 'Clave actual incorrecta', 'en_GB', 'Clave actual incorrecta'),
(null, 'Contenido', 'en_GB', 'Contenido'),
(null, 'Traducción', 'en_GB', 'Traducción'),
(null, 'pedidos_otros', 'en_GB', 'pedidos_otros'),
(null, 'pedidos_estatus', 'en_GB', 'pedidos_estatus'),
(null, 'contactos_otros', 'en_GB', 'contactos_otros'),
(null, 'permisos', 'en_GB', 'permisos'),
(null, 'bb', 'en_GB', 'bb'),
(null, 'aa', 'en_GB', 'aa'),
(null, 'Una vez la clave cambiada, tendra que volver a conectarse con la nueva clave.', 'en_GB', 'Una vez la clave cambiada, tendra que volver a conectarse con la nueva clave.'),
(null, 'cambiar_clave_otros', 'en_GB', 'cambiar_clave_otros'),
(null, 'Nueva Clave', 'en_GB', 'Nueva Clave'),
(null, 'Cambiar', 'en_GB', 'Cambiar'),
(null, '.', 'en_GB', '.'),
(null, 'Cambiar contacto', 'en_GB', 'Cambiar contacto'),
(null, 'Cancelar', 'en_GB', 'Cancelar'),
(null, 'Cambiar de clave', 'en_GB', 'Cambiar de clave'),
(null, 'ok', 'en_GB', 'ok'),
(null, 'Editar _idiomas', 'en_GB', 'Editar _idiomas'),
(null, 'Olvido su clave actual', 'en_GB', 'Olvido su clave actual'),
(null, 'Claves nueva y repetición no son iguales', 'en_GB', 'Claves nueva y repetición no son iguales'),
(null, 'root', 'en_GB', 'root'),
(null, 'gerente', 'en_GB', 'gerente'),
(null, 'centros', 'en_GB', 'centros'),
(null, 'administradores', 'en_GB', 'administradores'),
(null, 'Valor', 'en_GB', 'Valor'),
(null, 'Items', 'en_GB', 'Items'),
(null, 'Un nuevo pedido se a registrado en el sistema', 'en_GB', 'Un nuevo pedido se a registrado en el sistema'),
(null, 'Hola', 'en_GB', 'Hola'),
(null, 'Detalles del pedido', 'en_GB', 'Detalles del pedido'),
(null, 'Demo', 'en_GB', 'Demo'),
(null, 'export_sql', 'en_GB', 'export_sql'),
(null, 'export_cvs', 'en_GB', 'export_cvs'),
(null, 'implant', 'en_GB', 'implant'),
(null, 'coude_soupe', 'en_GB', 'coude_soupe'),
(null, 'fil_nylon', 'en_GB', 'fil_nylon'),
(null, 'pailletes', 'en_GB', 'pailletes'),
(null, 'cordon', 'en_GB', 'cordon'),
(null, 'hoka', 'en_GB', 'hoka'),
(null, 'mix', 'en_GB', 'mix'),
(null, 'anti_bacterie', 'en_GB', 'anti_bacterie'),
(null, 'thermosoft', 'en_GB', 'thermosoft'),
(null, 'thermotec', 'en_GB', 'thermotec'),
(null, 'silicone', 'en_GB', 'silicone'),
(null, 'resine', 'en_GB', 'resine'),
(null, 'iros', 'en_GB', 'iros'),
(null, 'prince_de_crave', 'en_GB', 'prince_de_crave'),
(null, 'epaulemnent', 'en_GB', 'epaulemnent'),
(null, 'conduit_seul', 'en_GB', 'conduit_seul'),
(null, 'coquille', 'en_GB', 'coquille'),
(null, 'invisible', 'en_GB', 'invisible'),
(null, 'anti_bruit', 'en_GB', 'anti_bruit'),
(null, 'dormir', 'en_GB', 'dormir'),
(null, 'natation', 'en_GB', 'natation'),
(null, 'custom_dume', 'en_GB', 'custom_dume'),
(null, 'slim_tube', 'en_GB', 'slim_tube'),
(null, 'rite', 'en_GB', 'rite'),
(null, 'bte', 'en_GB', 'bte'),
(null, 'dure', 'en_GB', 'dure'),
(null, 'molle', 'en_GB', 'molle'),
(null, 'grave', 'en_GB', 'grave'),
(null, 'moyenne', 'en_GB', 'moyenne'),
(null, 'legere', 'en_GB', 'legere'),
(null, 'remake', 'en_GB', 'remake'),
(null, 'payant', 'en_GB', 'payant'),
(null, 'Nuevo pedido vía la web', 'en_GB', 'Nuevo pedido vía la web'),
(null, 'notes', 'en_GB', 'Notas'),
(null, 'couleur_droite', 'en_GB', 'Color Der.'),
(null, 'models', 'en_GB', 'Modelos'),
(null, 'marques', 'en_GB', 'Marcas'),
(null, 'couleur_gauche', 'en_GB', 'Color Izq.'),
(null, 'ventilation_droite', 'en_GB', 'Ventilación der.'),
(null, 'ventilation_gauche', 'en_GB', 'Ventilación izq.'),
(null, 'du_numero', 'en_GB', 'De número'),
(null, 'pedidos_contacto', 'en_GB', 'Nombre del contacto'),
(null, 'pedidos_empresa', 'en_GB', 'Empresa'),
(null, 'pedidos_fecha', 'en_GB', 'Fecha del pedido'),
(null, 'pedidos_email', 'en_GB', 'Email'),
(null, 'pedidos_ref', 'en_GB', 'Referencia'),
(null, 'a', 'en_GB', 'a'),
(null, 'c', 'en_GB', 'c'),
(null, 'p', 'en_GB', 'p'),
(null, 'Lista de logs', 'en_GB', 'Lista de logs'),
(null, 'Id_pedido', 'en_GB', 'Id_pedido'),
(null, 'logs', 'en_GB', 'logs'),
(null, 'Argumento', 'en_GB', 'Argumento'),
(null, 'Pedido', 'en_GB', 'Pedido'),
(null, 'A', 'en_GB', 'A'),
(null, 'C', 'en_GB', 'C'),
(null, 'P', 'en_GB', 'P'),
(null, 'Nuevo logs', 'en_GB', 'Nuevo logs'),
(null, 'Todos', 'en_GB', 'Todos'),
(null, 'Acción', 'en_GB', 'Acción'),
(null, 'Página', 'en_GB', 'Página'),
(null, 'sin permiso', 'en_GB', 'sin permiso'),
(null, 'Mis pedidos', 'en_GB', 'Mis pedidos'),
(null, 'Estatus del pedidoBorrado', 'en_GB', 'Estatus del pedidoBorrado'),
(null, 'Ya no puede editar este pedido', 'en_GB', 'Ya no puede editar este pedido'),
(null, 'El pedido esta en siendo tratado, ya no puede editarlo', 'en_GB', 'El pedido esta en siendo tratado, ya no puede editarlo'),
(null, 'El pedido esta en siendo tratado', 'en_GB', 'El pedido esta en siendo tratado'),
(null, 'buscar_segun_estatus', 'en_GB', 'buscar_segun_estatus'),
(null, 'cambiar_estatus', 'en_GB', 'cambiar_estatus'),
(null, 'Borrado', 'en_GB', 'Borrado'),
(null, 'Enviado', 'en_GB', 'Enviado'),
(null, 'Borrar', 'en_GB', 'Borrar'),
(null, 'Enviado a contacto', 'en_GB', 'Enviado a contacto'),
(null, 'En proceso', 'en_GB', 'En proceso'),
(null, 'Registrado', 'en_GB', 'Registrado'),
(null, 'Formato texto', 'en_GB', 'Formato texto'),
(null, 'Bon n°:', 'en_GB', 'Bon n°:'),
(null, 'Bon n:', 'en_GB', 'Bon n:'),
(null, 'Busqueda detallada', 'en_GB', 'Busqueda detallada'),
(null, 'Número no existe', 'en_GB', 'Número no existe'),
(null, 'Pedidos Editar', 'en_GB', 'Pedidos Editar'),
(null, 'Mix', 'en_GB', 'Mix'),
(null, 'borrarr', 'en_GB', 'borrarr'),
(null, 'borrar', 'en_GB', 'borrar'),
(null, 'Pedido no le pertenece', 'en_GB', 'Pedido no le pertenece'),
(null, 'Bloqueado, No puede realizar pedidos', 'en_GB', 'Bloqueado, No puede realizar pedidos'),
(null, 'Activo, puede realizar pedidos', 'en_GB', 'Activo, puede realizar pedidos'),
(null, 'Cuenta bloqueada, no puede realizar pedidos', 'en_GB', 'Cuenta bloqueada, no puede realizar pedidos'),
(null, '-', 'en_GB', '-'),
(null, 'Por defecto se asignara el grupo centros a todo nuevo usuario', 'en_GB', 'Por defecto se asignara el grupo centros a todo nuevo usuario'),
(null, 'Usuarios', 'en_GB', 'Usuarios'),
(null, 't_usuarios', 'en_GB', 't_usuarios'),
(null, 'No se puede agregar usuarios root', 'en_GB', 'No se puede agregar usuarios root'),
(null, 'Olvido el email', 'en_GB', 'Olvido el email'),
(null, 'Editar _usuarios', 'en_GB', 'Editar _usuarios'),
(null, 'Olvido email', 'en_GB', 'Olvido email'),
(null, 'Email ya existe en la base de datos', 'en_GB', 'Email ya existe en la base de datos'),
(null, 'esss', 'en_GB', 'esss'),
(null, 'Si un contacto ya tiene pedidos registrados, no se puede cambiar de email', 'en_GB', 'Si un contacto ya tiene pedidos registrados, no se puede cambiar de email'),
(null, 'Pedidos', 'en_GB', 'Pedidos'),
(null, 'No, crear uno.', 'en_GB', 'No, crear uno.'),
(null, 'Este pedido no le pertenece', 'en_GB', 'Este pedido no le pertenece'),
(null, 'Nuevo contacto', 'en_GB', 'Nuevo contacto'),
(null, 'País', 'en_GB', 'País'),
(null, 'Dirección', 'en_GB', 'Dirección'),
(null, 'Empresa SPRL', 'en_GB', 'Empresa SPRL'),
(null, 'Belgique', 'en_GB', 'Belgique'),
(null, 'Código postal', 'en_GB', 'Código postal'),
(null, 'Sr. Sra. Srta. Dr. Dra. ...', 'en_GB', 'Sr. Sra. Srta. Dr. Dra. ...'),
(null, 'Nombres y apellidos', 'en_GB', 'Nombres y apellidos'),
(null, '123.123.123', 'en_GB', '123.123.123'),
(null, 'TVA', 'en_GB', 'TVA'),
(null, 'No, crear uno', 'en_GB', 'No, crear uno'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=contactos&c=index">contactos</a>, si el contacto ya tiene un login no aparecera en esta lista', 'en_GB', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=contactos&c=index">contactos</a>, si el contacto ya tiene un login no aparecera en esta lista'),
(null, 'Contactos sin usuario', 'en_GB', 'Contactos sin usuario'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=contactos&c=index">contactos</a>', 'en_GB', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de <a href="index.php?p=contactos&c=index">contactos</a>'),
(null, 'Para que un usuario tenga un login, debe estar registrado primero en la lista de contactos', 'en_GB', 'Para que un usuario tenga un login, debe estar registrado primero en la lista de contactos'),
(null, 'Nuevo usuario en el sistema', 'en_GB', 'Nuevo usuario en el sistema'),
(null, 'Tiene login', 'en_GB', 'Tiene login'),
(null, 'Si', 'en_GB', 'Si'),
(null, 'No', 'en_GB', 'No'),
(null, 'Nuevo usuario', 'en_GB', 'Nuevo usuario'),
(null, 'Lista de usuarios', 'en_GB', 'Lista de usuarios'),
(null, 'Resultados de su busqueda', 'en_GB', 'Resultados de su busqueda'),
(null, 'Ver', 'en_GB', 'Ver'),
(null, 'Repita aca la nueva clave', 'en_GB', 'Repita aca la nueva clave'),
(null, 'Letras, números, signos [&é#§çà, etc]', 'en_GB', 'Letras, números, signos [&é#§çà, etc]'),
(null, 'Letras, números, signos[&é#§çà, etc]', 'en_GB', 'Letras, números, signos[&é#§çà, etc]'),
(null, 'Su clave actual', 'en_GB', 'Su clave actual'),
(null, 'Repita', 'en_GB', 'Repita'),
(null, 'Nueva clave', 'en_GB', 'Nueva clave'),
(null, 'Clave Actual', 'en_GB', 'Clave Actual'),
(null, '123, sin ceros al inicio', 'en_GB', '123, sin ceros al inicio'),
(null, 'Bon', 'en_GB', 'Bon'),
(null, 'Id', 'en_GB', 'Id'),
(null, 'Editar _grupos', 'en_GB', 'Editar _grupos'),
(null, 'Grupos que el sistema tiene', 'en_GB', 'Grupos que el sistema tiene'),
(null, 'Una mala manipulación puede comprometer la seguridad de su sistema', 'en_GB', 'Una mala manipulación puede comprometer la seguridad de su sistema'),
(null, 'Si no esta seguro, no modifique nada porfavor', 'en_GB', 'Si no esta seguro, no modifique nada porfavor'),
(null, 'ID', 'en_GB', 'ID'),
(null, 'Editar contactos', 'en_GB', 'Editar contactos'),
(null, 'Tva', 'en_GB', 'Tva'),
(null, 'Login', 'en_GB', 'Login'),
(null, 'Av. Louise 265', 'en_GB', 'Av. Louise 265'),
(null, 'Bruxelles', 'en_GB', 'Bruxelles'),
(null, '1000', 'en_GB', '1000'),
(null, '123.456.789', 'en_GB', '123.456.789'),
(null, 'info@mail.com', 'en_GB', 'info@mail.com'),
(null, '+322123456', 'en_GB', '+322123456'),
(null, 'Número TVA', 'en_GB', 'Número TVA'),
(null, 'Numero TVA', 'en_GB', 'Numero TVA'),
(null, '000.111.222', 'en_GB', '000.111.222'),
(null, 'BE', 'en_GB', 'BE'),
(null, 'Numero de tva', 'en_GB', 'Numero de tva'),
(null, 'Nuevo contactos', 'en_GB', 'Nuevo contactos'),
(null, 'Es contacto', 'en_GB', 'Es contacto'),
(null, 'Fecha registro', 'en_GB', 'Fecha registro'),
(null, 'Numero documento', 'en_GB', 'Numero documento'),
(null, 'Ruc prefijo', 'en_GB', 'Ruc prefijo'),
(null, 'Tipo documento', 'en_GB', 'Tipo documento'),
(null, 'Lista de contactos', 'en_GB', 'Lista de contactos'),
(null, 'Estrellas', 'en_GB', 'Estrellas'),
(null, 'Es_contacto', 'en_GB', 'Es_contacto'),
(null, 'Fecha_registro', 'en_GB', 'Fecha_registro'),
(null, 'Tipo', 'en_GB', 'Tipo'),
(null, 'Fax', 'en_GB', 'Fax'),
(null, 'Tel', 'en_GB', 'Tel'),
(null, 'Pais', 'en_GB', 'Pais'),
(null, 'Provincia', 'en_GB', 'Provincia'),
(null, 'Ciudad', 'en_GB', 'Ciudad'),
(null, 'Cpostal', 'en_GB', 'Cpostal'),
(null, 'Direccion', 'en_GB', 'Direccion'),
(null, 'Saludo', 'en_GB', 'Saludo'),
(null, 'Numero_documento', 'en_GB', 'Numero_documento'),
(null, 'Ruc_prefijo', 'en_GB', 'Ruc_prefijo'),
(null, 'Tipo_documento', 'en_GB', 'Tipo_documento'),
(null, 'contactos', 'en_GB', 'contactos'),
(null, 'txt', 'en_GB', 'txt'),
(null, 'Editar pedidos', 'en_GB', 'Editar pedidos'),
(null, 'email', 'en_GB', 'email'),
(null, 'Al crear un nuevo grupo debe también configurar los permisos que este tendra en el sistema', 'en_GB', 'Al crear un nuevo grupo debe también configurar los permisos que este tendra en el sistema'),
(null, '', 'en_GB', ''),
(null, 'Editar _traducciones', 'en_GB', 'Editar _traducciones'),
(null, 'Nuevo _traducciones', 'en_GB', 'Nuevo _traducciones'),
(null, 'Registrar idioma', 'en_GB', 'Registrar idioma'),
(null, 'xx_XX', 'en_GB', 'xx_XX'),
(null, 'Idiomas', 'en_GB', 'Idiomas'),
(null, 'Esta acción puede comprometar la seguridad de su web, esta seguro?', 'en_GB', 'Esta acción puede comprometar la seguridad de su web, esta seguro?'),
(null, 'Editar _contenido', 'en_GB', 'Editar _contenido'),
(null, 'Editar _permisos', 'en_GB', 'Editar _permisos'),
(null, 'Nuevo _permisos', 'en_GB', 'Nuevo _permisos'),
(null, 'Nuevo _grupos', 'en_GB', 'Nuevo _grupos'),
(null, 'Contacte con el administrador', 'en_GB', 'Contacte con el administrador'),
(null, 'No disponible', 'en_GB', 'No disponible'),
(null, 'Ok', 'en_GB', 'Ok'),
(null, 'Info', 'en_GB', 'Info'),
(null, 'Alto', 'en_GB', 'Alto'),
(null, 'Ayuda', 'en_GB', 'Ayuda'),
(null, 'Atención', 'en_GB', 'Atención'),
(null, 'cambiar_clave', 'en_GB', 'cambiar_clave'),
(null, 'users', 'en_GB', 'users'),
(null, 'Nuevo', 'en_GB', 'Nuevo'),
(null, 'Nuevo _paginas', 'en_GB', 'Nuevo _paginas'),
(null, 'Editar _paginas', 'en_GB', 'Editar _paginas'),
(null, 'ver', 'en_GB', 'ver'),
(null, 'Nuevo _contenido', 'en_GB', 'Nuevo _contenido'),
(null, 'Lista de _traducciones', 'en_GB', 'Lista de _traducciones'),
(null, 'Traduccion', 'en_GB', 'Traduccion'),
(null, '_traducciones', 'en_GB', '_traducciones'),
(null, 'Lista de _paginas', 'en_GB', 'Lista de _paginas'),
(null, 'Nuevo _idiomas', 'en_GB', 'Nuevo _idiomas'),
(null, 'Resultados de su busqueda en ', 'en_GB', 'Resultados de su busqueda en '),
(null, 'buscar', 'en_GB', 'buscar'),
(null, 'Enviar', 'en_GB', 'Enviar'),
(null, 'Implante', 'en_GB', 'Implante'),
(null, 'Codo suave', 'en_GB', 'Codo suave'),
(null, 'Fil nylon', 'en_GB', 'Fil nylon'),
(null, 'Pailletes', 'en_GB', 'Pailletes'),
(null, 'Cordon', 'en_GB', 'Cordon'),
(null, 'Hoka', 'en_GB', 'Hoka'),
(null, 'Opciones', 'en_GB', 'Opciones'),
(null, 'Color derecha', 'en_GB', 'Color derecha'),
(null, 'Models', 'en_GB', 'Models'),
(null, 'Marques', 'en_GB', 'Marques'),
(null, 'RITE / SLIM TUBE', 'en_GB', 'RITE / SLIM TUBE'),
(null, 'Color izquierda', 'en_GB', 'Color izquierda'),
(null, 'Derecha', 'en_GB', 'Derecha'),
(null, 'Ventilation Droite', 'en_GB', 'Ventilation Droite'),
(null, 'Izquierda', 'en_GB', 'Izquierda'),
(null, 'Ventilación', 'en_GB', 'Ventilación'),
(null, 'Otro 2', 'en_GB', 'Otro 2'),
(null, 'Otro 1', 'en_GB', 'Otro 1'),
(null, 'Anti-Bactérie', 'en_GB', 'Anti-Bactérie'),
(null, 'Thermosoft', 'en_GB', 'Thermosoft'),
(null, 'Thermotec', 'en_GB', 'Thermotec'),
(null, 'Silicone', 'en_GB', 'Silicone'),
(null, 'Résine', 'en_GB', 'Résine'),
(null, 'Materiales', 'en_GB', 'Materiales'),
(null, 'Otro', 'en_GB', 'Otro'),
(null, 'Iros', 'en_GB', 'Iros'),
(null, 'Prince de Crave', 'en_GB', 'Prince de Crave'),
(null, 'Epaulement', 'en_GB', 'Epaulement'),
(null, 'Conduit seul', 'en_GB', 'Conduit seul'),
(null, 'Coquille', 'en_GB', 'Coquille'),
(null, 'Invisible', 'en_GB', 'Invisible'),
(null, 'Modelos', 'en_GB', 'Modelos'),
(null, 'Anti ruido', 'en_GB', 'Anti ruido'),
(null, 'Dormir', 'en_GB', 'Dormir'),
(null, 'Natation', 'en_GB', 'Natation'),
(null, 'Custom Dume', 'en_GB', 'Custom Dume'),
(null, 'Slim Tube', 'en_GB', 'Slim Tube'),
(null, 'Rite', 'en_GB', 'Rite'),
(null, 'Bte', 'en_GB', 'Bte'),
(null, 'Tipos', 'en_GB', 'Tipos'),
(null, 'Dura', 'en_GB', 'Dura'),
(null, 'Suave', 'en_GB', 'Suave'),
(null, 'Construcción orejera', 'en_GB', 'Construcción orejera'),
(null, 'Grave', 'en_GB', 'Grave'),
(null, 'Media', 'en_GB', 'Media'),
(null, 'Ligera', 'en_GB', 'Ligera'),
(null, 'Perdida auditiva', 'en_GB', 'Perdida auditiva'),
(null, 'De n°', 'en_GB', 'De n°'),
(null, 'Remake', 'en_GB', 'Remake'),
(null, 'Payant', 'en_GB', 'Payant'),
(null, 'Nombre del contacto', 'en_GB', 'Nombre del contacto'),
(null, 'Centro auditivo', 'en_GB', 'Centro auditivo'),
(null, 'Bon n°', 'en_GB', 'Bon n°'),
(null, 'Detalles', 'en_GB', 'Detalles'),
(null, 'Editar', 'en_GB', 'Editar'),
(null, 'Editar _menu', 'en_GB', 'Editar _menu'),
(null, 'editar', 'en_GB', 'editar'),
(null, 'Nuevo _menu', 'en_GB', 'Nuevo _menu'),
(null, 'Lista de _menu', 'en_GB', 'Lista de _menu'),
(null, 'Orden', 'en_GB', 'Orden'),
(null, 'Icono', 'en_GB', 'Icono'),
(null, 'Url', 'en_GB', 'Url'),
(null, 'Label', 'en_GB', 'Label'),
(null, 'Padre', 'en_GB', 'Padre'),
(null, 'Ubicacion', 'en_GB', 'Ubicacion'),
(null, '_paginas', 'en_GB', '_paginas'),
(null, '_menu', 'en_GB', '_menu'),
(null, 'Lista de _permisos', 'en_GB', 'Lista de _permisos'),
(null, 'Permiso', 'en_GB', 'Permiso'),
(null, 'Pagina', 'en_GB', 'Pagina'),
(null, '_permisos', 'en_GB', '_permisos'),
(null, 'Lista de _idiomas', 'en_GB', 'Lista de _idiomas'),
(null, 'Nombre', 'en_GB', 'Nombre'),
(null, 'Idioma', 'en_GB', 'Idioma'),
(null, '_idiomas', 'en_GB', '_idiomas'),
(null, 'Nuevo _usuarios', 'en_GB', 'Nuevo _usuarios'),
(null, 'Lista de _usuarios', 'en_GB', 'Lista de _usuarios'),
(null, 'Clave', 'en_GB', 'Clave'),
(null, 'Usuario', 'en_GB', 'Usuario'),
(null, '_usuarios', 'en_GB', '_usuarios'),
(null, 'Registrar', 'en_GB', 'Registrar'),
(null, 'Bloqueado', 'en_GB', 'Bloqueado'),
(null, 'Activo', 'en_GB', 'Activo'),
(null, 'aaaa-mm-dd', 'en_GB', 'aaaa-mm-dd'),
(null, 'Nuevo pedidos', 'en_GB', 'Nuevo pedidos'),
(null, 'crear', 'en_GB', 'crear'),
(null, 'Lista de pedidos', 'en_GB', 'Lista de pedidos'),
(null, 'Estatus', 'en_GB', 'Estatus'),
(null, 'Notas', 'en_GB', 'Notas'),
(null, 'Fecha', 'en_GB', 'Fecha'),
(null, 'Descripcion', 'en_GB', 'Descripcion'),
(null, 'Email', 'en_GB', 'Email'),
(null, 'Contacto', 'en_GB', 'Contacto'),
(null, 'Empresa', 'en_GB', 'Empresa'),
(null, 'Ref', 'en_GB', 'Ref'),
(null, 'pedidos', 'en_GB', 'pedidos'),
(null, 'Lista de _grupos', 'en_GB', 'Lista de _grupos'),
(null, 'Grupo', 'en_GB', 'Grupo'),
(null, '_grupos', 'en_GB', '_grupos'),
(null, 'Accion', 'en_GB', 'Acción'),
(null, 'Nueva', 'en_GB', 'Nueva'),
(null, 'Lista de _contenido', 'en_GB', 'Lista de _contenido'),
(null, 'Contexto', 'en_GB', 'Contexto'),
(null, 'Frase', 'en_GB', 'Frase'),
(null, 'Buscar', 'en_GB', 'Buscar'),
(null, 'Lista', 'en_GB', 'Lista'),
(null, '_contenido', 'en_GB', 'contenido'),
(null, 'index', 'en_GB', 'index'),
(null, 'home', 'en_GB', 'home'),
(null, 'Inicio', 'en_GB', 'Inicio'),
(null, 'Logout', 'en_GB', 'Logout'),
(null, 'Cambiar clave', 'en_GB', 'Cambiar clave');    